In [2]:
import numpy as np

In [7]:
arr1 = np.array([.1, .2, .132, .203])
print(arr1 + 1)
print(arr1 * 2)
print(arr1 / 3)
print(arr1**2)
print(arr1 * arr1)
arr1+=1
arr2 = arr1 + 3
arr1 <= arr2

[1.1   1.2   1.132 1.203]
[0.2   0.4   0.264 0.406]
[0.03333333 0.06666667 0.044      0.06766667]
[0.01     0.04     0.017424 0.041209]
[0.01     0.04     0.017424 0.041209]


array([ True,  True,  True,  True])