In [1]:
import numpy as np

In [9]:
x_points = np.arange(-5, 5)
y_points = np.arange(-10, 0)
np.add(x_points+4, y_points+3)

array([-8, -6, -4, -2,  0,  2,  4,  6,  8, 10])

In [16]:
x_arr = np.ones(10)
y_arr = np.zeros_like(x_arr)
cond = np.array([True, False]*5)
results = np.where(cond, x_arr, y_arr)

array([1., 0., 1., 0., 1., 0., 1., 0., 1., 0.])

In [32]:
np.isin(np.ones(10), 1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [34]:
np.isin('ivan', 'ivan')

array(True)