In [1]:
import numpy as np

In [3]:
bord = np.array([np.array([i]*8) for i in range(8)])
bord[[1, 3, 4]]


array([[1, 1, 1, 1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4]])

In [6]:
bord[[-1, -2, -3]][:,:4]

array([[7, 7, 7, 7],
       [6, 6, 6, 6],
       [5, 5, 5, 5]])

In [10]:
data = np.arange(8*6).reshape(8,6)
# [1, 45, 16]
data[[0,-1, 2], [1, 3, 4]]

array([ 1, 45, 16])