In [2]:
import numpy as np

In [7]:
data = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [ ]:
# attribute shape and dtype

In [9]:
data.shape

(3, 3)

In [10]:
data.dtype

dtype('int64')

In [ ]:
# new ndarray

In [18]:
data1 = np.array([[[1.0, 2.2, 3.3, 3], 
                  [0., 0., 0., 3]]])

print(data1.ndim) # return number axes
print(data1.shape) # return numbers elements in axes as array


3
(1, 2, 4)


In [19]:
data1.dtype

dtype('float64')

In [ ]:
# foo np.zeros and np.one

In [24]:
#         z, y, x
np.zeros((1, 2, 3))

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
np.empty([1,2,3])

array([[[0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
np.arange(0, 10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [29]:
np.arange(10, 1, -0.5)

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5])

In [35]:
a = np.array([1, 2, 3])
b = a 
print(id(a), id(b))
a[0] = -1
print(a, b)

2540089447440 2540089447440
[-1  2  3] [-1  2  3]


In [37]:
a = np.array([1, 2, 3])
b = np.array(a)
print(f'a: {id(a)} b:{id(b)}')
a[1] = -1
print(a, b)

a: 2540089450416 b:2540089452720
[ 1 -1  3] [1 2 3]


In [38]:
a = np.array([1, 2, 3])
b = np.asanyarray(a)
print(f'a: {id(a)} b:{id(b)}')
a[1] = -1
print(a, b)

a: 2540089453680 b:2540089453680
[ 1 -1  3] [ 1 -1  3]


In [40]:
a = [1, 2, 3]
b = np.asanyarray(a)
print(f'a: {id(a)} b:{id(b)}')
b[1] = 0
print(a, b)


a: 2540088953024 b:2540089452912
[1, 2, 3] [1 0 3]


In [79]:
x,y = np.random.randint(0, 3, 2)
a = np.ones((y, x))
np.ones_like(a)

array([], shape=(0, 1), dtype=float64)

In [ ]:
x,y = np.random.randint(0, 3, 2)
a = np.zeros((y, x))
np.zeros_like(a)

In [86]:
x,y = np.random.randint(0, 3, 2)
a = np.empty((y, x))
np.empty_like(a)

array([[1.5e-323]])

In [128]:
x, y = np.random.randint(0, 3, 2)
a = np.full((y, x), ['#']*x)
a

array([], shape=(1, 0), dtype=float64)

In [131]:
a = np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [133]:
b = np.identity(5)
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [141]:
a = np.zeros((1, 2, 3), dtype='int64')
string = a.astype('str')
string

array([[['0', '0', '0'],
        ['0', '0', '0']]], dtype='<U21')