In [1]:
import numpy as np

In [26]:
arr = np.array([[*range(8)]]*8)
print(arr)
print(arr.sum(axis=0))

[[0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]
 [0 1 2 3 4 5 6 7]]
[28 28 28 28 28 28 28 28]


In [22]:
sum(range(8))

28