In [78]:
import numpy as np
np.random.seed(3)

In [2]:
arr = np.arange(1,11)

In [3]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [4]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [8]:
x = np.random.standard_normal(100)
y = np.random.standard_normal(100)
np.maximum(x,y)

array([ 0.33971662, -0.29270437,  1.23852532, -0.28277263,  2.13658481,
        1.13595767, -0.67178404,  0.09979655,  0.0666037 ,  1.76715695,
        1.00234881,  0.71021841,  0.59319512, -0.13165615,  0.80262685,
        0.3537665 , -0.26671187,  0.11421218,  0.95752518, -0.24487092,
        1.02897923,  2.12168862, -0.19112228,  1.33913429,  2.38332472,
        0.92953121,  1.92052323,  0.52732297, -0.27539958,  0.17645551,
        0.07517357,  0.73765027,  1.83185711,  0.28482814, -0.14932511,
        1.84554355,  0.18592395,  1.27355572,  1.17425446, -0.9221831 ,
       -0.14167264,  0.1931112 ,  1.04504603,  0.83536594,  1.49282897,
       -0.48905504,  1.35938856,  1.57953931,  0.45300913,  0.62629638,
       -0.30066218, -0.02321274,  3.08181607,  1.50015143,  0.28901586,
        1.05837376, -0.44168195,  1.43677608,  0.00669128,  1.21358054,
       -0.01272422,  0.51131766,  1.7363979 ,  0.04870631,  2.25930291,
        1.48618948, -0.19945068,  1.858042  ,  0.36281962,  1.46

In [12]:
arr = np.arange(1,11) + np.random.rand(10)
arr

array([ 1.60049118,  2.24104986,  3.49483808,  4.07762164,  5.56722873,
        6.757899  ,  7.57541466,  8.32368367,  9.83920758, 10.65932885])

In [16]:
remainder, whole_part = np.modf(arr)
remainder, whole_part

(array([0.60049118, 0.24104986, 0.49483808, 0.07762164, 0.56722873,
        0.757899  , 0.57541466, 0.32368367, 0.83920758, 0.65932885]),
 array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [27]:
new_arr = np.arange(1,11, dtype='float64') 
np.sqrt(new_arr, out=new_arr)
new_arr

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [36]:
z_numbers = np.array([i+i*1j for i in range(10)])
new_arr = np.empty_like(z_numbers, dtype='float64')
np.abs(z_numbers, out=new_arr)

array([ 0.        ,  1.41421356,  2.82842712,  4.24264069,  5.65685425,
        7.07106781,  8.48528137,  9.89949494, 11.3137085 , 12.72792206])

In [126]:
arr = np.array([np.random.randint(0, 100, 42), np.zeros(42)])
arr_test = arr.reshape(84)
arr_test[0] = 1000
np.random.shuffle(arr_test)
print(arr)

[[  99.   96.    3.   70.   78.    0.   45.    0.   31.    0.   34.   93.
     0.    0.   83.    0.    0.    0.   16.    0.    0.    0.    0.    0.
    62.   18.    0.    0.    0.    0.   25.    0.    0.   15.   41.   36.
    16.   27.   14.    0.    0.   85.]
 [1000.    0.   35.   37.   88.   89.    0.   85.    0.    0.    0.   15.
    47.    0.    6.    0.    0.    0.   82.   75.    0.    0.   83.    0.
     0.   81.    0.    0.   54.   85.   99.   54.   96.    0.    0.    0.
     0.    0.   79.    0.   82.    0.]]
